# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'battery_select.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_batterySelect(object):
    def setupUi(self, batterySelect):
        batterySelect.setObjectName(_fromUtf8("batterySelect"))
        batterySelect.resize(513, 567)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(batterySelect.sizePolicy().hasHeightForWidth())
        batterySelect.setSizePolicy(sizePolicy)
        batterySelect.setAutoFillBackground(False)
        self.verticalLayout = QtGui.QVBoxLayout(batterySelect)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.mainLayout = QtGui.QVBoxLayout()
        self.mainLayout.setObjectName(_fromUtf8("mainLayout"))
        self.sessionInfoLayout = QtGui.QVBoxLayout()
        self.sessionInfoLayout.setObjectName(_fromUtf8("sessionInfoLayout"))
        self.sessionInfoText = QtGui.QLabel(batterySelect)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sessionInfoText.sizePolicy().hasHeightForWidth())
        self.sessionInfoText.setSizePolicy(sizePolicy)
        self.sessionInfoText.setTextFormat(QtCore.Qt.AutoText)
        self.sessionInfoText.setObjectName(_fromUtf8("sessionInfoText"))
        self.sessionInfoLayout.addWidget(self.sessionInfoText)
        self.sessionInfoColumnLayout = QtGui.QHBoxLayout()
        self.sessionInfoColumnLayout.setObjectName(_fromUtf8("sessionInfoColumnLayout"))
        self.sessionInfoLabelLayout = QtGui.QVBoxLayout()
        self.sessionInfoLabelLayout.setObjectName(_fromUtf8("sessionInfoLabelLayout"))
        self.raText = QtGui.QLabel(batterySelect)
        self.raText.setObjectName(_fromUtf8("raText"))
        self.sessionInfoLabelLayout.addWidget(self.raText)
        self.subNumText = QtGui.QLabel(batterySelect)
        self.subNumText.setObjectName(_fromUtf8("subNumText"))
        self.sessionInfoLabelLayout.addWidget(self.subNumText)
        self.experimentIDText = QtGui.QLabel(batterySelect)
        self.experimentIDText.setObjectName(_fromUtf8("experimentIDText"))
        self.sessionInfoLabelLayout.addWidget(self.experimentIDText)
        self.conditionText = QtGui.QLabel(batterySelect)
        self.conditionText.setObjectName(_fromUtf8("conditionText"))
        self.sessionInfoLabelLayout.addWidget(self.conditionText)
        self.ageText = QtGui.QLabel(batterySelect)
        self.ageText.setObjectName(_fromUtf8("ageText"))
        self.sessionInfoLabelLayout.addWidget(self.ageText)
        self.sexText = QtGui.QLabel(batterySelect)
        self.sexText.setObjectName(_fromUtf8("sexText"))
        self.sessionInfoLabelLayout.addWidget(self.sexText)
        self.sessionInfoColumnLayout.addLayout(self.sessionInfoLabelLayout)
        self.sessionInfoInputLayout = QtGui.QVBoxLayout()
        self.sessionInfoInputLayout.setObjectName(_fromUtf8("sessionInfoInputLayout"))
        self.raBox = QtGui.QLineEdit(batterySelect)
        self.raBox.setObjectName(_fromUtf8("raBox"))
        self.sessionInfoInputLayout.addWidget(self.raBox)
        self.subNumBox = QtGui.QLineEdit(batterySelect)
        self.subNumBox.setObjectName(_fromUtf8("subNumBox"))
        self.sessionInfoInputLayout.addWidget(self.subNumBox)
        self.experimentIDBox = QtGui.QLineEdit(batterySelect)
        self.experimentIDBox.setObjectName(_fromUtf8("experimentIDBox"))
        self.sessionInfoInputLayout.addWidget(self.experimentIDBox)
        self.conditionBox = QtGui.QLineEdit(batterySelect)
        self.conditionBox.setObjectName(_fromUtf8("conditionBox"))
        self.sessionInfoInputLayout.addWidget(self.conditionBox)
        self.ageBox = QtGui.QLineEdit(batterySelect)
        self.ageBox.setObjectName(_fromUtf8("ageBox"))
        self.sessionInfoInputLayout.addWidget(self.ageBox)
        self.sexLayout = QtGui.QHBoxLayout()
        self.sexLayout.setContentsMargins(-1, -1, -1, 0)
        self.sexLayout.setObjectName(_fromUtf8("sexLayout"))
        self.maleRadio = QtGui.QRadioButton(batterySelect)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maleRadio.sizePolicy().hasHeightForWidth())
        self.maleRadio.setSizePolicy(sizePolicy)
        self.maleRadio.setObjectName(_fromUtf8("maleRadio"))
        self.sexLayout.addWidget(self.maleRadio)
        self.femaleRadio = QtGui.QRadioButton(batterySelect)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.femaleRadio.sizePolicy().hasHeightForWidth())
        self.femaleRadio.setSizePolicy(sizePolicy)
        self.femaleRadio.setObjectName(_fromUtf8("femaleRadio"))
        self.sexLayout.addWidget(self.femaleRadio)
        self.sessionInfoInputLayout.addLayout(self.sexLayout)
        self.sessionInfoColumnLayout.addLayout(self.sessionInfoInputLayout)
        self.sessionInfoLayout.addLayout(self.sessionInfoColumnLayout)
        self.mainLayout.addLayout(self.sessionInfoLayout)
        self.sessionLine = QtGui.QFrame(batterySelect)
        self.sessionLine.setLineWidth(1)
        self.sessionLine.setFrameShape(QtGui.QFrame.HLine)
        self.sessionLine.setFrameShadow(QtGui.QFrame.Sunken)
        self.sessionLine.setObjectName(_fromUtf8("sessionLine"))
        self.mainLayout.addWidget(self.sessionLine)
        self.batteryLayout = QtGui.QVBoxLayout()
        self.batteryLayout.setObjectName(_fromUtf8("batteryLayout"))
        self.batterySelectText = QtGui.QLabel(batterySelect)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.batterySelectText.sizePolicy().hasHeightForWidth())
        self.batterySelectText.setSizePolicy(sizePolicy)
        self.batterySelectText.setScaledContents(True)
        self.batterySelectText.setObjectName(_fromUtf8("batterySelectText"))
        self.batteryLayout.addWidget(self.batterySelectText)
        self.taskOrderLayout = QtGui.QHBoxLayout()
        self.taskOrderLayout.setContentsMargins(-1, -1, -1, 10)
        self.taskOrderLayout.setObjectName(_fromUtf8("taskOrderLayout"))
        self.reorderText = QtGui.QLabel(batterySelect)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.reorderText.setFont(font)
        self.reorderText.setObjectName(_fromUtf8("reorderText"))
        self.taskOrderLayout.addWidget(self.reorderText)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.taskOrderLayout.addItem(spacerItem)
        self.randomOrderCheck = QtGui.QCheckBox(batterySelect)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.randomOrderCheck.sizePolicy().hasHeightForWidth())
        self.randomOrderCheck.setSizePolicy(sizePolicy)
        self.randomOrderCheck.setChecked(False)
        self.randomOrderCheck.setObjectName(_fromUtf8("randomOrderCheck"))
        self.taskOrderLayout.addWidget(self.randomOrderCheck)
        self.batteryLayout.addLayout(self.taskOrderLayout)
        self.selectionLayout = QtGui.QHBoxLayout()
        self.selectionLayout.setContentsMargins(-1, -1, -1, 10)
        self.selectionLayout.setObjectName(_fromUtf8("selectionLayout"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.selectionLayout.addItem(spacerItem1)
        self.selectAllButton = QtGui.QPushButton(batterySelect)
        self.selectAllButton.setObjectName(_fromUtf8("selectAllButton"))
        self.selectionLayout.addWidget(self.selectAllButton)
        self.deselectAllButton = QtGui.QPushButton(batterySelect)
        self.deselectAllButton.setObjectName(_fromUtf8("deselectAllButton"))
        self.selectionLayout.addWidget(self.deselectAllButton)
        self.batteryLayout.addLayout(self.selectionLayout)
        self.taskListLayout = QtGui.QHBoxLayout()
        self.taskListLayout.setContentsMargins(-1, -1, -1, 0)
        self.taskListLayout.setObjectName(_fromUtf8("taskListLayout"))
        self.taskList = QtGui.QListWidget(batterySelect)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.taskList.setFont(font)
        self.taskList.setProperty("showDropIndicator", False)
        self.taskList.setDragEnabled(True)
        self.taskList.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.taskList.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.taskList.setAlternatingRowColors(True)
        self.taskList.setMovement(QtGui.QListView.Snap)
        self.taskList.setObjectName(_fromUtf8("taskList"))
        item = QtGui.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.taskList.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.taskList.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.taskList.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.taskList.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.taskList.addItem(item)
        self.taskListLayout.addWidget(self.taskList)
        self.reorderButtonLayout = QtGui.QVBoxLayout()
        self.reorderButtonLayout.setContentsMargins(0, -1, -1, -1)
        self.reorderButtonLayout.setSpacing(6)
        self.reorderButtonLayout.setObjectName(_fromUtf8("reorderButtonLayout"))
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.reorderButtonLayout.addItem(spacerItem2)
        self.upButton = QtGui.QPushButton(batterySelect)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upButton.sizePolicy().hasHeightForWidth())
        self.upButton.setSizePolicy(sizePolicy)
        self.upButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.upButton.setObjectName(_fromUtf8("upButton"))
        self.reorderButtonLayout.addWidget(self.upButton)
        self.downButton = QtGui.QPushButton(batterySelect)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.downButton.sizePolicy().hasHeightForWidth())
        self.downButton.setSizePolicy(sizePolicy)
        self.downButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.downButton.setObjectName(_fromUtf8("downButton"))
        self.reorderButtonLayout.addWidget(self.downButton)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.reorderButtonLayout.addItem(spacerItem3)
        self.taskListLayout.addLayout(self.reorderButtonLayout)
        self.batteryLayout.addLayout(self.taskListLayout)
        self.mainLayout.addLayout(self.batteryLayout)
        self.saveLoadLayout = QtGui.QHBoxLayout()
        self.saveLoadLayout.setObjectName(_fromUtf8("saveLoadLayout"))
        self.startButton = QtGui.QPushButton(batterySelect)
        self.startButton.setObjectName(_fromUtf8("startButton"))
        self.saveLoadLayout.addWidget(self.startButton)
        self.cancelButton = QtGui.QPushButton(batterySelect)
        self.cancelButton.setObjectName(_fromUtf8("cancelButton"))
        self.saveLoadLayout.addWidget(self.cancelButton)
        self.mainLayout.addLayout(self.saveLoadLayout)
        self.verticalLayout.addLayout(self.mainLayout)

        self.retranslateUi(batterySelect)
        QtCore.QMetaObject.connectSlotsByName(batterySelect)

    def retranslateUi(self, batterySelect):
        batterySelect.setWindowTitle(_translate("batterySelect", "Cognitive Battery", None))
        self.sessionInfoText.setText(_translate("batterySelect", "<html><head/><body><p><span style=\" font-weight:600;\">Session information:</span></p></body></html>", None))
        self.raText.setText(_translate("batterySelect", "Research Assistant:", None))
        self.subNumText.setText(_translate("batterySelect", "Subject #:", None))
        self.experimentIDText.setText(_translate("batterySelect", "Experiment ID:", None))
        self.conditionText.setText(_translate("batterySelect", "Condition:", None))
        self.ageText.setText(_translate("batterySelect", "Age:", None))
        self.sexText.setText(_translate("batterySelect", "Sex:", None))
        self.maleRadio.setText(_translate("batterySelect", "Male", None))
        self.femaleRadio.setText(_translate("batterySelect", "Female", None))
        self.batterySelectText.setText(_translate("batterySelect", "<html><head/><body><p><span style=\" font-weight:600;\">Task selection:</span></p></body></html>", None))
        self.reorderText.setText(_translate("batterySelect", "(use the Up/Down buttons to set adminstration order)", None))
        self.randomOrderCheck.setText(_translate("batterySelect", "Random order", None))
        self.selectAllButton.setText(_translate("batterySelect", "Select All", None))
        self.deselectAllButton.setText(_translate("batterySelect", "Deselect All", None))
        __sortingEnabled = self.taskList.isSortingEnabled()
        self.taskList.setSortingEnabled(False)
        item = self.taskList.item(0)
        item.setText(_translate("batterySelect", "Attention Network Test (ANT)", None))
        item = self.taskList.item(1)
        item.setText(_translate("batterySelect", "Sustained Attention to Response Task (SART)", None))
        item = self.taskList.item(2)
        item.setText(_translate("batterySelect", "Digit Span (backwards)", None))
        item = self.taskList.item(3)
        item.setText(_translate("batterySelect", "Mental Rotation Task", None))
        item = self.taskList.item(4)
        item.setText(_translate("batterySelect", "Raven\'s Progressive Matrices", None))
        self.taskList.setSortingEnabled(__sortingEnabled)
        self.upButton.setText(_translate("batterySelect", "Up", None))
        self.downButton.setText(_translate("batterySelect", "Down", None))
        self.startButton.setText(_translate("batterySelect", "Start", None))
        self.cancelButton.setText(_translate("batterySelect", "Cancel", None))

