# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'project_new_window_qt.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_NewProjectWindow(object):
    def setupUi(self, NewProjectWindow):
        NewProjectWindow.setObjectName("NewProjectWindow")
        NewProjectWindow.setWindowModality(QtCore.Qt.NonModal)
        NewProjectWindow.resize(426, 163)
        NewProjectWindow.setSizeGripEnabled(True)
        NewProjectWindow.setModal(True)
        self.horizontalLayout = QtWidgets.QHBoxLayout(NewProjectWindow)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelLayout = QtWidgets.QVBoxLayout()
        self.labelLayout.setObjectName("labelLayout")
        self.researcherLabel = QtWidgets.QLabel(NewProjectWindow)
        self.researcherLabel.setObjectName("researcherLabel")
        self.labelLayout.addWidget(self.researcherLabel)
        self.projectNameLabel = QtWidgets.QLabel(NewProjectWindow)
        self.projectNameLabel.setObjectName("projectNameLabel")
        self.labelLayout.addWidget(self.projectNameLabel)
        self.horizontalLayout_2.addLayout(self.labelLayout)
        self.valueLayout = QtWidgets.QVBoxLayout()
        self.valueLayout.setObjectName("valueLayout")
        self.researcherValue = QtWidgets.QLineEdit(NewProjectWindow)
        self.researcherValue.setClearButtonEnabled(True)
        self.researcherValue.setObjectName("researcherValue")
        self.valueLayout.addWidget(self.researcherValue)
        self.projectNameValue = QtWidgets.QLineEdit(NewProjectWindow)
        self.projectNameValue.setInputMask("")
        self.projectNameValue.setPlaceholderText("")
        self.projectNameValue.setClearButtonEnabled(True)
        self.projectNameValue.setObjectName("projectNameValue")
        self.valueLayout.addWidget(self.projectNameValue)
        self.horizontalLayout_2.addLayout(self.valueLayout)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.dirLabel = QtWidgets.QLabel(NewProjectWindow)
        self.dirLabel.setObjectName("dirLabel")
        self.verticalLayout_2.addWidget(self.dirLabel)
        self.dirSelectLayout = QtWidgets.QHBoxLayout()
        self.dirSelectLayout.setObjectName("dirSelectLayout")
        self.dirSelectButton = QtWidgets.QPushButton(NewProjectWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dirSelectButton.sizePolicy().hasHeightForWidth())
        self.dirSelectButton.setSizePolicy(sizePolicy)
        self.dirSelectButton.setObjectName("dirSelectButton")
        self.dirSelectLayout.addWidget(self.dirSelectButton)
        self.dirValue = QtWidgets.QLabel(NewProjectWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dirValue.sizePolicy().hasHeightForWidth())
        self.dirValue.setSizePolicy(sizePolicy)
        self.dirValue.setText("")
        self.dirValue.setObjectName("dirValue")
        self.dirSelectLayout.addWidget(self.dirValue)
        self.verticalLayout_2.addLayout(self.dirSelectLayout)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttonLayout.addItem(spacerItem1)
        self.createButton = QtWidgets.QPushButton(NewProjectWindow)
        self.createButton.setObjectName("createButton")
        self.buttonLayout.addWidget(self.createButton)
        self.cancelButton = QtWidgets.QPushButton(NewProjectWindow)
        self.cancelButton.setObjectName("cancelButton")
        self.buttonLayout.addWidget(self.cancelButton)
        self.verticalLayout.addLayout(self.buttonLayout)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(NewProjectWindow)
        QtCore.QMetaObject.connectSlotsByName(NewProjectWindow)

    def retranslateUi(self, NewProjectWindow):
        _translate = QtCore.QCoreApplication.translate
        NewProjectWindow.setWindowTitle(_translate("NewProjectWindow", "New Project Bookmark"))
        self.researcherLabel.setText(_translate("NewProjectWindow", "Researcher:"))
        self.projectNameLabel.setText(_translate("NewProjectWindow", "Project Name:"))
        self.dirLabel.setText(_translate("NewProjectWindow", "Select project directory:"))
        self.dirSelectButton.setText(_translate("NewProjectWindow", "..."))
        self.createButton.setText(_translate("NewProjectWindow", "Create"))
        self.cancelButton.setText(_translate("NewProjectWindow", "Cancel"))

