# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings_window_qt.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SettingsDialog(object):
    def setupUi(self, SettingsDialog):
        SettingsDialog.setObjectName("SettingsDialog")
        SettingsDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        SettingsDialog.resize(416, 364)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SettingsDialog.sizePolicy().hasHeightForWidth())
        SettingsDialog.setSizePolicy(sizePolicy)
        SettingsDialog.setSizeGripEnabled(True)
        SettingsDialog.setModal(True)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(SettingsDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.settings_main_layout = QtWidgets.QVBoxLayout()
        self.settings_main_layout.setObjectName("settings_main_layout")
        self.scrollArea = QtWidgets.QScrollArea(SettingsDialog)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.Box)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 392, 309))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.settings_toolbox = QtWidgets.QToolBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.settings_toolbox.setFont(font)
        self.settings_toolbox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.settings_toolbox.setObjectName("settings_toolbox")
        self.general_page = QtWidgets.QWidget()
        self.general_page.setGeometry(QtCore.QRect(0, 0, 374, 156))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.general_page.sizePolicy().hasHeightForWidth())
        self.general_page.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.general_page.setFont(font)
        self.general_page.setObjectName("general_page")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.general_page)
        self.verticalLayout_7.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.settings_general_layout = QtWidgets.QVBoxLayout()
        self.settings_general_layout.setContentsMargins(10, -1, 10, -1)
        self.settings_general_layout.setObjectName("settings_general_layout")
        self.settings_task_fullscreen_checkbox = QtWidgets.QCheckBox(self.general_page)
        self.settings_task_fullscreen_checkbox.setObjectName("settings_task_fullscreen_checkbox")
        self.settings_general_layout.addWidget(self.settings_task_fullscreen_checkbox)
        self.settings_task_borderless_checkbox = QtWidgets.QCheckBox(self.general_page)
        self.settings_task_borderless_checkbox.setObjectName("settings_task_borderless_checkbox")
        self.settings_general_layout.addWidget(self.settings_task_borderless_checkbox)
        self.settings_task_size = QtWidgets.QHBoxLayout()
        self.settings_task_size.setObjectName("settings_task_size")
        self.settings_task_width_label = QtWidgets.QLabel(self.general_page)
        self.settings_task_width_label.setObjectName("settings_task_width_label")
        self.settings_task_size.addWidget(self.settings_task_width_label)
        self.settings_task_width_value = QtWidgets.QLineEdit(self.general_page)
        self.settings_task_width_value.setObjectName("settings_task_width_value")
        self.settings_task_size.addWidget(self.settings_task_width_value)
        self.settings_task_height_label = QtWidgets.QLabel(self.general_page)
        self.settings_task_height_label.setObjectName("settings_task_height_label")
        self.settings_task_size.addWidget(self.settings_task_height_label)
        self.settings_task_height_value = QtWidgets.QLineEdit(self.general_page)
        self.settings_task_height_value.setObjectName("settings_task_height_value")
        self.settings_task_size.addWidget(self.settings_task_height_value)
        self.settings_general_layout.addLayout(self.settings_task_size)
        self.settings_task_beep_checkbox = QtWidgets.QCheckBox(self.general_page)
        self.settings_task_beep_checkbox.setObjectName("settings_task_beep_checkbox")
        self.settings_general_layout.addWidget(self.settings_task_beep_checkbox)
        self.verticalLayout_7.addLayout(self.settings_general_layout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem)
        self.settings_toolbox.addItem(self.general_page, "")
        self.ant_page = QtWidgets.QWidget()
        self.ant_page.setGeometry(QtCore.QRect(0, 0, 374, 156))
        self.ant_page.setObjectName("ant_page")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.ant_page)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ant_form = QtWidgets.QFormLayout()
        self.ant_form.setContentsMargins(10, -1, 10, -1)
        self.ant_form.setObjectName("ant_form")
        self.settings_ant_blocks_label = QtWidgets.QLabel(self.ant_page)
        self.settings_ant_blocks_label.setObjectName("settings_ant_blocks_label")
        self.ant_form.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.settings_ant_blocks_label)
        self.settings_ant_blocks_value = QtWidgets.QLineEdit(self.ant_page)
        self.settings_ant_blocks_value.setObjectName("settings_ant_blocks_value")
        self.ant_form.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.settings_ant_blocks_value)
        self.horizontalLayout.addLayout(self.ant_form)
        self.settings_toolbox.addItem(self.ant_page, "")
        self.flanker_page = QtWidgets.QWidget()
        self.flanker_page.setGeometry(QtCore.QRect(0, 0, 374, 156))
        self.flanker_page.setObjectName("flanker_page")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.flanker_page)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.flanker_form = QtWidgets.QFormLayout()
        self.flanker_form.setContentsMargins(10, -1, 10, -1)
        self.flanker_form.setObjectName("flanker_form")
        self.settings_flanker_dark = QtWidgets.QCheckBox(self.flanker_page)
        self.settings_flanker_dark.setObjectName("settings_flanker_dark")
        self.flanker_form.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.settings_flanker_dark)
        self.settings_flanker_compat_label = QtWidgets.QLabel(self.flanker_page)
        self.settings_flanker_compat_label.setObjectName("settings_flanker_compat_label")
        self.flanker_form.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.settings_flanker_compat_label)
        self.settings_flanker_compat_value = QtWidgets.QLineEdit(self.flanker_page)
        self.settings_flanker_compat_value.setObjectName("settings_flanker_compat_value")
        self.flanker_form.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.settings_flanker_compat_value)
        self.settings_flanker_incompat_label = QtWidgets.QLabel(self.flanker_page)
        self.settings_flanker_incompat_label.setObjectName("settings_flanker_incompat_label")
        self.flanker_form.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.settings_flanker_incompat_label)
        self.settings_flanker_incompat_value = QtWidgets.QLineEdit(self.flanker_page)
        self.settings_flanker_incompat_value.setObjectName("settings_flanker_incompat_value")
        self.flanker_form.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.settings_flanker_incompat_value)
        self.settings_flanker_order_label = QtWidgets.QLabel(self.flanker_page)
        self.settings_flanker_order_label.setObjectName("settings_flanker_order_label")
        self.flanker_form.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.settings_flanker_order_label)
        self.settings_flanker_order_group = QtWidgets.QVBoxLayout()
        self.settings_flanker_order_group.setObjectName("settings_flanker_order_group")
        self.settings_flanker_order_compat = QtWidgets.QRadioButton(self.flanker_page)
        self.settings_flanker_order_compat.setCheckable(True)
        self.settings_flanker_order_compat.setChecked(True)
        self.settings_flanker_order_compat.setObjectName("settings_flanker_order_compat")
        self.settings_flanker_order_group.addWidget(self.settings_flanker_order_compat)
        self.settings_flanker_order_incompat = QtWidgets.QRadioButton(self.flanker_page)
        self.settings_flanker_order_incompat.setObjectName("settings_flanker_order_incompat")
        self.settings_flanker_order_group.addWidget(self.settings_flanker_order_incompat)
        self.settings_flanker_order_choose = QtWidgets.QRadioButton(self.flanker_page)
        self.settings_flanker_order_choose.setObjectName("settings_flanker_order_choose")
        self.settings_flanker_order_group.addWidget(self.settings_flanker_order_choose)
        self.flanker_form.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.settings_flanker_order_group)
        self.verticalLayout.addLayout(self.flanker_form)
        self.settings_toolbox.addItem(self.flanker_page, "")
        self.ravens_page = QtWidgets.QWidget()
        self.ravens_page.setGeometry(QtCore.QRect(0, 0, 374, 156))
        self.ravens_page.setObjectName("ravens_page")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.ravens_page)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(10, -1, 10, -1)
        self.formLayout.setObjectName("formLayout")
        self.settings_ravens_start_label = QtWidgets.QLabel(self.ravens_page)
        self.settings_ravens_start_label.setObjectName("settings_ravens_start_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.settings_ravens_start_label)
        self.settings_ravens_start_value = QtWidgets.QLineEdit(self.ravens_page)
        self.settings_ravens_start_value.setObjectName("settings_ravens_start_value")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.settings_ravens_start_value)
        self.settings_ravens_trials_label = QtWidgets.QLabel(self.ravens_page)
        self.settings_ravens_trials_label.setObjectName("settings_ravens_trials_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.settings_ravens_trials_label)
        self.settings_ravens_trials_value = QtWidgets.QLineEdit(self.ravens_page)
        self.settings_ravens_trials_value.setObjectName("settings_ravens_trials_value")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.settings_ravens_trials_value)
        self.verticalLayout_4.addLayout(self.formLayout)
        self.settings_toolbox.addItem(self.ravens_page, "")
        self.sternberg_page = QtWidgets.QWidget()
        self.sternberg_page.setGeometry(QtCore.QRect(0, 0, 374, 156))
        self.sternberg_page.setObjectName("sternberg_page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.sternberg_page)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.sternberg_form = QtWidgets.QFormLayout()
        self.sternberg_form.setContentsMargins(10, -1, 10, -1)
        self.sternberg_form.setObjectName("sternberg_form")
        self.settings_sternberg_blocks_label = QtWidgets.QLabel(self.sternberg_page)
        self.settings_sternberg_blocks_label.setObjectName("settings_sternberg_blocks_label")
        self.sternberg_form.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.settings_sternberg_blocks_label)
        self.settings_sternberg_blocks_value = QtWidgets.QLineEdit(self.sternberg_page)
        self.settings_sternberg_blocks_value.setObjectName("settings_sternberg_blocks_value")
        self.sternberg_form.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.settings_sternberg_blocks_value)
        self.verticalLayout_3.addLayout(self.sternberg_form)
        self.settings_toolbox.addItem(self.sternberg_page, "")
        self.verticalLayout_5.addWidget(self.settings_toolbox)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.settings_main_layout.addWidget(self.scrollArea)
        self.settings_button_layout = QtWidgets.QHBoxLayout()
        self.settings_button_layout.setObjectName("settings_button_layout")
        self.settings_save_button = QtWidgets.QPushButton(SettingsDialog)
        self.settings_save_button.setAutoDefault(False)
        self.settings_save_button.setObjectName("settings_save_button")
        self.settings_button_layout.addWidget(self.settings_save_button)
        self.settings_cancel_button = QtWidgets.QPushButton(SettingsDialog)
        self.settings_cancel_button.setAutoDefault(False)
        self.settings_cancel_button.setObjectName("settings_cancel_button")
        self.settings_button_layout.addWidget(self.settings_cancel_button)
        self.settings_main_layout.addLayout(self.settings_button_layout)
        self.verticalLayout_2.addLayout(self.settings_main_layout)

        self.retranslateUi(SettingsDialog)
        self.settings_toolbox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(SettingsDialog)

    def retranslateUi(self, SettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        SettingsDialog.setWindowTitle(_translate("SettingsDialog", "Settings"))
        self.settings_task_fullscreen_checkbox.setText(_translate("SettingsDialog", "Fullscreen"))
        self.settings_task_borderless_checkbox.setText(_translate("SettingsDialog", "Borderless"))
        self.settings_task_width_label.setText(_translate("SettingsDialog", "Width:"))
        self.settings_task_width_value.setStatusTip(_translate("SettingsDialog", "Width of the task windows"))
        self.settings_task_height_label.setText(_translate("SettingsDialog", "Height:"))
        self.settings_task_height_value.setStatusTip(_translate("SettingsDialog", "Height of the task windows"))
        self.settings_task_beep_checkbox.setText(_translate("SettingsDialog", "Play beep after each task"))
        self.settings_toolbox.setItemText(self.settings_toolbox.indexOf(self.general_page), _translate("SettingsDialog", "General"))
        self.settings_ant_blocks_label.setText(_translate("SettingsDialog", "Number of blocks:"))
        self.settings_toolbox.setItemText(self.settings_toolbox.indexOf(self.ant_page), _translate("SettingsDialog", "Attention Network Test"))
        self.settings_flanker_dark.setToolTip(_translate("SettingsDialog", "Use dark colour scheme. White text on black background"))
        self.settings_flanker_dark.setText(_translate("SettingsDialog", "Dark mode"))
        self.settings_flanker_compat_label.setText(_translate("SettingsDialog", "Number of compatible blocks:"))
        self.settings_flanker_compat_value.setToolTip(_translate("SettingsDialog", "Compatible block: respond in direction of center arrow"))
        self.settings_flanker_incompat_label.setText(_translate("SettingsDialog", "Number of incompatible blocks:"))
        self.settings_flanker_incompat_value.setToolTip(_translate("SettingsDialog", "Incompatible block: respond in opposite direction to center arrow"))
        self.settings_flanker_order_label.setText(_translate("SettingsDialog", "Block order:"))
        self.settings_flanker_order_compat.setToolTip(_translate("SettingsDialog", "Display compatible blocks first"))
        self.settings_flanker_order_compat.setText(_translate("SettingsDialog", "Compatible first"))
        self.settings_flanker_order_incompat.setToolTip(_translate("SettingsDialog", "Display incompatible blocks first"))
        self.settings_flanker_order_incompat.setText(_translate("SettingsDialog", "Incompatible first"))
        self.settings_flanker_order_choose.setToolTip(_translate("SettingsDialog", "Choose block order when task starts"))
        self.settings_flanker_order_choose.setText(_translate("SettingsDialog", "Choose"))
        self.settings_toolbox.setItemText(self.settings_toolbox.indexOf(self.flanker_page), _translate("SettingsDialog", "Eriksen Flanker Task"))
        self.settings_ravens_start_label.setText(_translate("SettingsDialog", "Starting image #:"))
        self.settings_ravens_trials_label.setText(_translate("SettingsDialog", "Number of trials:"))
        self.settings_toolbox.setItemText(self.settings_toolbox.indexOf(self.ravens_page), _translate("SettingsDialog", "Raven\'s Progressive Matrices"))
        self.settings_sternberg_blocks_label.setText(_translate("SettingsDialog", "Number of blocks:"))
        self.settings_toolbox.setItemText(self.settings_toolbox.indexOf(self.sternberg_page), _translate("SettingsDialog", "Sternberg Task"))
        self.settings_save_button.setStatusTip(_translate("SettingsDialog", "Save settings"))
        self.settings_save_button.setText(_translate("SettingsDialog", "Save"))
        self.settings_cancel_button.setStatusTip(_translate("SettingsDialog", "Cancel"))
        self.settings_cancel_button.setText(_translate("SettingsDialog", "Cancel"))

