# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings_window_qt.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SettingsDialog(object):
    def setupUi(self, SettingsDialog):
        SettingsDialog.setObjectName("SettingsDialog")
        SettingsDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        SettingsDialog.resize(415, 296)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SettingsDialog.sizePolicy().hasHeightForWidth())
        SettingsDialog.setSizePolicy(sizePolicy)
        SettingsDialog.setSizeGripEnabled(True)
        SettingsDialog.setModal(True)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(SettingsDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.settings_main_layout = QtWidgets.QVBoxLayout()
        self.settings_main_layout.setObjectName("settings_main_layout")
        self.scrollArea = QtWidgets.QScrollArea(SettingsDialog)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.Box)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 391, 241))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.settings_toolbox = QtWidgets.QToolBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.settings_toolbox.setFont(font)
        self.settings_toolbox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.settings_toolbox.setObjectName("settings_toolbox")
        self.task_windows_page = QtWidgets.QWidget()
        self.task_windows_page.setGeometry(QtCore.QRect(0, 0, 373, 115))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.task_windows_page.sizePolicy().hasHeightForWidth())
        self.task_windows_page.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.task_windows_page.setFont(font)
        self.task_windows_page.setObjectName("task_windows_page")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.task_windows_page)
        self.verticalLayout_7.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(10, -1, 10, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.settings_task_fullscreen_checkbox = QtWidgets.QCheckBox(self.task_windows_page)
        self.settings_task_fullscreen_checkbox.setObjectName("settings_task_fullscreen_checkbox")
        self.verticalLayout.addWidget(self.settings_task_fullscreen_checkbox)
        self.settings_task_borderless_checkbox = QtWidgets.QCheckBox(self.task_windows_page)
        self.settings_task_borderless_checkbox.setObjectName("settings_task_borderless_checkbox")
        self.verticalLayout.addWidget(self.settings_task_borderless_checkbox)
        self.settings_task_size = QtWidgets.QHBoxLayout()
        self.settings_task_size.setObjectName("settings_task_size")
        self.settings_task_width_label = QtWidgets.QLabel(self.task_windows_page)
        self.settings_task_width_label.setObjectName("settings_task_width_label")
        self.settings_task_size.addWidget(self.settings_task_width_label)
        self.settings_task_width_value = QtWidgets.QLineEdit(self.task_windows_page)
        self.settings_task_width_value.setObjectName("settings_task_width_value")
        self.settings_task_size.addWidget(self.settings_task_width_value)
        self.settings_task_height_label = QtWidgets.QLabel(self.task_windows_page)
        self.settings_task_height_label.setObjectName("settings_task_height_label")
        self.settings_task_size.addWidget(self.settings_task_height_label)
        self.settings_task_height_value = QtWidgets.QLineEdit(self.task_windows_page)
        self.settings_task_height_value.setObjectName("settings_task_height_value")
        self.settings_task_size.addWidget(self.settings_task_height_value)
        self.verticalLayout.addLayout(self.settings_task_size)
        self.verticalLayout_7.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem)
        self.settings_toolbox.addItem(self.task_windows_page, "")
        self.ant_page = QtWidgets.QWidget()
        self.ant_page.setGeometry(QtCore.QRect(0, 0, 373, 115))
        self.ant_page.setObjectName("ant_page")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.ant_page)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ant_form = QtWidgets.QFormLayout()
        self.ant_form.setContentsMargins(10, -1, 10, -1)
        self.ant_form.setObjectName("ant_form")
        self.settings_ant_blocks_label = QtWidgets.QLabel(self.ant_page)
        self.settings_ant_blocks_label.setObjectName("settings_ant_blocks_label")
        self.ant_form.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.settings_ant_blocks_label)
        self.settings_ant_blocks_value = QtWidgets.QLineEdit(self.ant_page)
        self.settings_ant_blocks_value.setObjectName("settings_ant_blocks_value")
        self.ant_form.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.settings_ant_blocks_value)
        self.horizontalLayout.addLayout(self.ant_form)
        self.settings_toolbox.addItem(self.ant_page, "")
        self.ravens_page = QtWidgets.QWidget()
        self.ravens_page.setObjectName("ravens_page")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.ravens_page)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(10, -1, 10, -1)
        self.formLayout.setObjectName("formLayout")
        self.settings_ravens_start_label = QtWidgets.QLabel(self.ravens_page)
        self.settings_ravens_start_label.setObjectName("settings_ravens_start_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.settings_ravens_start_label)
        self.settings_ravens_start_value = QtWidgets.QLineEdit(self.ravens_page)
        self.settings_ravens_start_value.setObjectName("settings_ravens_start_value")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.settings_ravens_start_value)
        self.settings_ravens_trials_label = QtWidgets.QLabel(self.ravens_page)
        self.settings_ravens_trials_label.setObjectName("settings_ravens_trials_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.settings_ravens_trials_label)
        self.settings_ravens_trials_value = QtWidgets.QLineEdit(self.ravens_page)
        self.settings_ravens_trials_value.setObjectName("settings_ravens_trials_value")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.settings_ravens_trials_value)
        self.verticalLayout_4.addLayout(self.formLayout)
        self.settings_toolbox.addItem(self.ravens_page, "")
        self.sternberg_page = QtWidgets.QWidget()
        self.sternberg_page.setGeometry(QtCore.QRect(0, 0, 373, 115))
        self.sternberg_page.setObjectName("sternberg_page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.sternberg_page)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.sternberg_form = QtWidgets.QFormLayout()
        self.sternberg_form.setContentsMargins(10, -1, 10, -1)
        self.sternberg_form.setObjectName("sternberg_form")
        self.settings_sternberg_blocks_label = QtWidgets.QLabel(self.sternberg_page)
        self.settings_sternberg_blocks_label.setObjectName("settings_sternberg_blocks_label")
        self.sternberg_form.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.settings_sternberg_blocks_label)
        self.settings_sternberg_blocks_value = QtWidgets.QLineEdit(self.sternberg_page)
        self.settings_sternberg_blocks_value.setObjectName("settings_sternberg_blocks_value")
        self.sternberg_form.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.settings_sternberg_blocks_value)
        self.verticalLayout_3.addLayout(self.sternberg_form)
        self.settings_toolbox.addItem(self.sternberg_page, "")
        self.verticalLayout_5.addWidget(self.settings_toolbox)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.settings_main_layout.addWidget(self.scrollArea)
        self.settings_button_layout = QtWidgets.QHBoxLayout()
        self.settings_button_layout.setObjectName("settings_button_layout")
        self.settings_save_button = QtWidgets.QPushButton(SettingsDialog)
        self.settings_save_button.setAutoDefault(False)
        self.settings_save_button.setObjectName("settings_save_button")
        self.settings_button_layout.addWidget(self.settings_save_button)
        self.settings_cancel_button = QtWidgets.QPushButton(SettingsDialog)
        self.settings_cancel_button.setAutoDefault(False)
        self.settings_cancel_button.setObjectName("settings_cancel_button")
        self.settings_button_layout.addWidget(self.settings_cancel_button)
        self.settings_main_layout.addLayout(self.settings_button_layout)
        self.verticalLayout_2.addLayout(self.settings_main_layout)

        self.retranslateUi(SettingsDialog)
        self.settings_toolbox.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(SettingsDialog)

    def retranslateUi(self, SettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        SettingsDialog.setWindowTitle(_translate("SettingsDialog", "Settings"))
        self.settings_task_fullscreen_checkbox.setText(_translate("SettingsDialog", "Fullscreen"))
        self.settings_task_borderless_checkbox.setText(_translate("SettingsDialog", "Borderless"))
        self.settings_task_width_label.setText(_translate("SettingsDialog", "Width:"))
        self.settings_task_width_value.setStatusTip(_translate("SettingsDialog", "Width of the task windows"))
        self.settings_task_height_label.setText(_translate("SettingsDialog", "Height:"))
        self.settings_task_height_value.setStatusTip(_translate("SettingsDialog", "Height of the task windows"))
        self.settings_toolbox.setItemText(self.settings_toolbox.indexOf(self.task_windows_page), _translate("SettingsDialog", "Task Windows"))
        self.settings_ant_blocks_label.setText(_translate("SettingsDialog", "Number of blocks:"))
        self.settings_toolbox.setItemText(self.settings_toolbox.indexOf(self.ant_page), _translate("SettingsDialog", "Attention Network Test"))
        self.settings_ravens_start_label.setText(_translate("SettingsDialog", "Starting image #:"))
        self.settings_ravens_trials_label.setText(_translate("SettingsDialog", "Number of trials:"))
        self.settings_toolbox.setItemText(self.settings_toolbox.indexOf(self.ravens_page), _translate("SettingsDialog", "Raven\'s Progressive Matrices"))
        self.settings_sternberg_blocks_label.setText(_translate("SettingsDialog", "Number of blocks:"))
        self.settings_toolbox.setItemText(self.settings_toolbox.indexOf(self.sternberg_page), _translate("SettingsDialog", "Sternberg Task"))
        self.settings_save_button.setStatusTip(_translate("SettingsDialog", "Save settings"))
        self.settings_save_button.setText(_translate("SettingsDialog", "Save"))
        self.settings_cancel_button.setStatusTip(_translate("SettingsDialog", "Cancel"))
        self.settings_cancel_button.setText(_translate("SettingsDialog", "Cancel"))

