# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'update_dialog_qt.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(396, 156)
        Dialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title.sizePolicy().hasHeightForWidth())
        self.title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setOpenExternalLinks(False)
        self.title.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.title.setObjectName("title")
        self.verticalLayout.addWidget(self.title)
        self.mainLayout = QtWidgets.QHBoxLayout()
        self.mainLayout.setObjectName("mainLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.info = QtWidgets.QLabel(Dialog)
        self.info.setText("")
        self.info.setObjectName("info")
        self.verticalLayout_4.addWidget(self.info)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.latest_label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.latest_label.setFont(font)
        self.latest_label.setObjectName("latest_label")
        self.gridLayout_4.addWidget(self.latest_label, 0, 0, 1, 1)
        self.current_label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.current_label.setFont(font)
        self.current_label.setObjectName("current_label")
        self.gridLayout_4.addWidget(self.current_label, 1, 0, 1, 1)
        self.latest_value = QtWidgets.QLabel(Dialog)
        self.latest_value.setText("")
        self.latest_value.setObjectName("latest_value")
        self.gridLayout_4.addWidget(self.latest_value, 0, 1, 1, 1)
        self.current_value = QtWidgets.QLabel(Dialog)
        self.current_value.setText("")
        self.current_value.setObjectName("current_value")
        self.gridLayout_4.addWidget(self.current_value, 1, 1, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_4)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.buttonsLayout = QtWidgets.QHBoxLayout()
        self.buttonsLayout.setObjectName("buttonsLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttonsLayout.addItem(spacerItem2)
        self.btn_update = QtWidgets.QPushButton(Dialog)
        self.btn_update.setEnabled(False)
        self.btn_update.setObjectName("btn_update")
        self.buttonsLayout.addWidget(self.btn_update)
        self.btn_close = QtWidgets.QPushButton(Dialog)
        self.btn_close.setObjectName("btn_close")
        self.buttonsLayout.addWidget(self.btn_close)
        self.verticalLayout_4.addLayout(self.buttonsLayout)
        self.mainLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout.addLayout(self.mainLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Software Update"))
        self.title.setText(_translate("Dialog", "Software Update"))
        self.latest_label.setText(_translate("Dialog", "Latest version:"))
        self.current_label.setText(_translate("Dialog", "Current version:"))
        self.btn_update.setText(_translate("Dialog", "Update"))
        self.btn_close.setText(_translate("Dialog", "Close"))

